development:
  adapter: postgresql
  encoding: unicode
  database: floodhousing_development
  pool: 5
  username: floodhousing
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: floodhousing_test
  pool: 5
  username: floodhousing
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: floodhousing_production
  pool: 5
  username: floodhousing
  password:

cucumber:
  <<: *test