#!/usr/bin/env ruby

def prompt_for prompt
  print "Please enter the #{prompt} > "
  gets.chomp
end

def confirm
  if ENV['SOFTLY_SOFTLY']
    print 'Continue? '
    exit 0 if gets.slice(0..0).downcase == 'n'
  end
end

def run commands
  commands.each do |command|
    puts command
    confirm
    system command
    raise "command failed with status #{$?}" unless $? == 0
  end
end

name = ARGV.shift || prompt_for('heroku project name')

run <<EOF.lines
heroku create #{name}
heroku config:add BUNDLE_WITHOUT=\"development:test\" --app #{name}
heroku config:add RACK_ENV=preproduction --app #{name}
heroku config:add DEFAULT_HOST=#{name}.heroku.com --app #{name}
heroku addons:add sendgrid:free --app #{name}
heroku addons:add releases:basic --app #{name}
heroku addons:add newrelic:bronze --app #{name}
git push git@heroku.com:#{name}.git master
heroku rake db:migrate --app #{name}
open http://#{name}.heroku.com
EOF

puts <<EOF
# set the following environment variable
export HEROKU_TEST=#{name}
# for subsequent deployments
. profile
dtest
EOF