#!/usr/bin/env ruby

i=0
loop do
  total, available, unconfirmed, contacts = 0, 0, 0, 0
  `heroku rake floods:report:listings --app ozfloodhelp`.each_line do |line|
    total = $1.to_i if line =~ /Total listings:\t\t(\d+)/
    available = $1.to_i if line =~ /Available listings:\t(\d+)/
    unconfirmed = $1.to_i if line =~ /Unconfirmed listings:\t(\d+)/
    contacts = $1.to_i if line =~ /Total contacts:\t\t(\d+)/
  end
  unavailable = total - (available+unconfirmed)
  if i%5 == 0 
    puts "timestamp, human time, unconfirmed,available,unavailable,contacts"
  end
  puts "#{Time.new.to_i},#{unconfirmed},#{available},#{unavailable},#{contacts}"
  sleep 60
  i = i+1
end
